name: Pull request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      tag: pr-${{ github.event.pull_request.number }}
